services:
  - type: web
    name: mathfluency
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --timeout 120 app:create_app()
    postDeployCommand: |
      if [ "$RENDER" = "true" ]; then
        echo "Running database migrations..."
        flask db upgrade
        echo "Creating test users..."
        python create_test_users.py --production
      fi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_DEBUG
        value: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
