"""remove multiplicand columns from quiz

Revision ID: 156bcb432c7a
Revises: 72c0870b907d
Create Date: 2025-02-22 12:30:19.174307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156bcb432c7a'
down_revision = '72c0870b907d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiplicand1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('multiplicand2', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('multiplicand2')
        batch_op.drop_column('multiplicand1')

    # ### end Alembic commands ###
