"""Add class_code to Class model

Revision ID: 2a984f65740f
Revises: aed5b95cc253
Create Date: 2025-01-01 22:49:56.192804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a984f65740f'
down_revision = 'aed5b95cc253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_code', sa.String(length=8), nullable=True))
        batch_op.create_unique_constraint('uq_class_code', ['class_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_constraint('uq_class_code', type_='unique')
        batch_op.drop_column('class_code')

    # ### end Alembic commands ###
