"""Add active_session table

Revision ID: 511851bb8d17
Revises: 02e87ffced57
Create Date: 2025-01-04 18:48:25.794654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511851bb8d17'
down_revision = '02e87ffced57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_session')
    # ### end Alembic commands ###
