"""Add start and start time to assignment

Revision ID: aed5b95cc253
Revises: 83fb8fd03409
Create Date: 2024-12-31 17:36:32.499414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed5b95cc253'
down_revision = '83fb8fd03409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_progress', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('started')

    # ### end Alembic commands ###
