"""Add Google OAuth fields to User model

Revision ID: f78b2b97322c
Revises: 2a984f65740f
Create Date: 2025-01-02 00:52:13.581155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78b2b97322c'
down_revision = '2a984f65740f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
